impl
ChristinaFomenko/gophermart pull request #1
Opened 2022-08-10 14:54 UTC by ChristinaFomenko

2022-08-11 17:17 UTC, sergeysergeevru requested changes
Привет! В общем и целом отлично, есть только критичный момент с отсутствием атомарности списания средств: нужна общая транзакция на процесс, так бы принял. Спасибо)

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/repository/broker_repository.go
> +}
непонятна потребность этой обертки у BrokerRepository нет ни одного собственного метода.

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/repository/psql/psql.go
> +`)
у тебя же даже есть файлы с миграциями, значит о них знаешь.  Стоило бы запускать миграции во время старта приложения. Текущий подход принесет трудности если придется менять схему в будущем.

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/controller/http/handlers/token.go
> +	w.Header().Set("Authorization", "BEARER "+token)
nit: Bearer обычно не капсом пишут)

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/controller/http/handlers/accruals.go
> +		http.Error(w, errs.InternalServerError, http.StatusInternalServerError)
проверку ошибки предпочел бы через errors.Is на случай если где-нибудь будет ошибка обернута

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/controller/http/handlers/auth.go
> +	ctx := context.Background()
контекст можно/лучше брать из r.Context(), тогда если захочется прокидывать что-то в контексте (например requestId или traceId) то задача будет проще

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/controller/http/handlers/auth.go
> +	ctx := context.Background()
в остальных методах аналогично

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/repository/psql/auth.go
> +}
для аутентификации пользователя я бы вытаскивал пользователя по логину, а потом бы проверял пароль. Собственно тут две причины. Можно замораживать пользователя после нескольких неверных попыток аутентификации, а так же если пользоваться bcrypt, scrypt и тому подобными подходами, то мы не сможем сгенерировать зашифрованный пароль без соли, которая хранится в базе.

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/service/auth.go
> +}
имеет место быть, но как минимум пароль стоит посолить или, лучше, использовать специальными функциями хранения паролей bcrypt/scrypt/pbkdf2. При текущем подходе с взломом могут справиться радужные таблицы

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/repository/psql/auth.go
> +	return userID, nil
user передается указателем и в таком случае можем просто обновить поле
```suggestion
	user.Id = int(output.Int32)
	return nil
```

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/repository/psql/balance.go
> +	_ = row.Scan(&withdrawals)
все таки ошибку стоит проверить иначе можно наткнуться на случай когда она была и мы отдаем дефолтное значение

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/service/balance.go
> +	err := w.repo.DeductPoints(ctx, order)
все это должно выполняться атомарно. В текущий момент, если мы запустим несколько запросов параллельно, то может возникнуть ситуация что мы спишем больше чем можем. Например если доступных у нас 5 баллов, а один запрос на 4 балла, второй на 3. Если оба реквеста получат баланс до выполнения DeductPoints, то мы спишем и 5-4-3 в итоге.

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/service/balance.go
> +	if order.Sum > accruals-withdrawn {
а если доступных средств у нас как раз на сумму заказа? Похоже тут должно быть нестрогое неравенство)

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/broker/model/status.go
> +}
если что можно еще так определять типы
```go
type Status string
```

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/broker/model/status.go
> +}
хотя может это у тебя попытка сделать что-то вроде enum

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/service/accruals.go
> +	userIDinDB := a.repo.GetUserIDByNumberOrder(ctx, order.Number)
ошибку стоит сюда тоже возвращать, иначе может случится что нам вернулся 0 потому что ошибка была

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/broker/service/service.go
> +	err := b.getJSONOrderFromAccrual(url, &orderAccrual)
можно сделать просто клиент для accrual отдельный, с сигнатурой
```go
type AccrualProvider interface {
          GetOrderByNumber(num string )(*model.Order, error)
}
```
Выйдет удобнее и можно мокать если захочется;

2022-08-11 17:17 UTC, sergeysergeevru commented on internal/broker/service/service.go
> +			go b.getOrdersAccrualWorker(order)
можно просто было запустить нужное количество воркеров каждый из которых читает канал b.chOrdersForProcessing. Тогда код будет проще выглядеть без механизмов синхронизации на основе chLimitWorkers

2022-08-17 15:03 UTC, ChristinaFomenko commented
> Привет! В общем и целом отлично, есть только критичный момент с отсутствием атомарности списания средств: нужна общая транзакция на процесс, так бы принял. Спасибо)

привет!) @sergeysergeevru а можно ли добиться атомарности в данной реализации только добавлением sql-запросов?
я понимаю, что такое атомарность списания средств, но еще не сталкивалась с таким на практике.  надеялась, что применение транзакций в sql-запросов будет достаточно) как тогда должна выглядеть общая  транзакция?

2022-08-18 16:24 UTC, sergeysergeevru requested changes
Постарался описать проблему, если будут вопросы напиши. У тебя теперь даже есть возможность какой-нибудь паттерн внедрить)

2022-08-18 16:24 UTC, sergeysergeevru commented on internal/service/balance.go
> +}
описал в чем проблема, (описание работы DeductPoints для иллюстрации, вроде код там ок))
![1660839657176](https://user-images.githubusercontent.com/12248824/185445256-7c1cdba5-8792-4cfe-b8d4-b82e682a4e8f.jpg)

2022-08-24 07:13 UTC, merged